"use client";

import * as React from "react";
import Link from "next/link";
import { useStore, useSnapshot } from "@/lib/store";
import { generateInsights, type Insight, type InsightKind } from "@/lib/engines/insights";
import { isSent } from "@/lib/engines/analytics";
import { PageHeader, SectionTitle } from "@/components/shared";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { EmptyState } from "@/components/ui/misc";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import {
  GraduationCap,
  FileText,
  Type,
  Clock,
  CalendarDays,
  Ruler,
  Building2,
  Megaphone,
  Reply,
  Sparkles,
  TrendingUp,
  Sigma,
  BarChart3,
  Lightbulb,
  BookOpen,
  type LucideIcon,
} from "lucide-react";

/* ---- deterministic mapping from insight kind -> icon + accent color ---- */
const KIND_META: Record<InsightKind, { icon: LucideIcon; color: string; label: string }> = {
  best_template: { icon: FileText, color: "var(--chart-1)", label: "Template" },
  best_subject: { icon: Type, color: "var(--chart-2)", label: "Subject line" },
  best_time: { icon: Clock, color: "var(--chart-3)", label: "Send time" },
  best_day: { icon: CalendarDays, color: "var(--chart-4)", label: "Send day" },
  best_length: { icon: Ruler, color: "var(--chart-5)", label: "Email length" },
  best_industry: { icon: Building2, color: "var(--chart-6)", label: "Industry" },
  best_campaign: { icon: Megaphone, color: "var(--primary)", label: "Campaign" },
  best_followup_delay: { icon: Reply, color: "var(--info)", label: "Follow-up" },
  trend: { icon: TrendingUp, color: "var(--success)", label: "Trend" },
};

const CONFIDENCE_META: Record<
  Insight["confidence"],
  { variant: "success" | "warning" | "muted"; label: string; order: number }
> = {
  high: { variant: "success", label: "High confidence", order: 0 },
  medium: { variant: "warning", label: "Medium confidence", order: 1 },
  low: { variant: "muted", label: "Low confidence", order: 2 },
};

export default function LearningPage() {
  const snap = useSnapshot();
  const companies = useStore((s) => s.companies);

  const insights = React.useMemo(
    () => generateInsights(snap, companies),
    [snap, companies],
  );

  /* sort high-confidence first, then by sample size (most-supported first) */
  const sorted = React.useMemo(
    () =>
      [...insights].sort((a, b) => {
        const c = CONFIDENCE_META[a.confidence].order - CONFIDENCE_META[b.confidence].order;
        return c !== 0 ? c : b.sampleSize - a.sampleSize;
      }),
    [insights],
  );

  /* headline findings for the hero strip — pick the four "playbook" kinds */
  const hero = React.useMemo(() => {
    const byKind = new Map(insights.map((i) => [i.kind, i]));
    const order: InsightKind[] = ["best_template", "best_time", "best_day", "best_length"];
    return order
      .map((k) => byKind.get(k))
      .filter((x): x is Insight => Boolean(x))
      .slice(0, 4);
  }, [insights]);

  const counts = React.useMemo(() => {
    const total = insights.length;
    const high = insights.filter((i) => i.confidence === "high").length;
    const totalSample = snap.messages.filter(isSent).length;
    return { total, high, totalSample };
  }, [insights, snap.messages]);

  return (
    <div className="space-y-6">
      <PageHeader
        icon={GraduationCap}
        title="Learning Center"
        description="What's working across your outbound — ranked by statistical confidence, not guesswork."
        actions={
          <Link href="/analytics">
            <Button variant="outline">
              <BarChart3 className="size-4" /> Full analytics
            </Button>
          </Link>
        }
      />

      {/* Explainer — insights are computed, not AI */}
      <Card className="border-primary/20 bg-primary/[0.03]">
        <CardContent className="flex flex-wrap items-start gap-3 p-4">
          <div className="flex size-9 shrink-0 items-center justify-center rounded-lg border border-primary/20 bg-card text-primary">
            <Sigma className="size-4.5" />
          </div>
          <div className="min-w-0 flex-1">
            <p className="text-sm font-medium">Every finding here is math, not a model.</p>
            <p className="mt-0.5 text-sm text-muted-foreground">
              Insights are ranked with{" "}
              <span className="font-medium text-foreground">Wilson score lower bounds</span> and
              reply-rate comparisons over your real send history — the same statistics used for
              conversion tests. Nothing is generated by an LLM, so results are deterministic and
              reproducible. Confidence reflects how many sends back each claim.
            </p>
          </div>
          {counts.total > 0 && (
            <div className="flex shrink-0 items-center gap-2">
              <Badge variant="secondary" dot="var(--muted-foreground)">
                {counts.total} finding{counts.total === 1 ? "" : "s"}
              </Badge>
              <Badge variant="success" dot="var(--success)">
                {counts.high} high-confidence
              </Badge>
            </div>
          )}
        </CardContent>
      </Card>

      {insights.length === 0 ? (
        <EmptyState
          icon={<Lightbulb className="size-9" />}
          title="Not enough data to learn from yet"
          description="Insights unlock once campaigns have sent and replies start landing. Send a few hundred emails and the Learning Center will surface your best templates, times, and days automatically — all computed with statistics, no AI."
          action={
            <Link href="/campaigns?new=1">
              <Button>
                <Megaphone className="size-4" /> Launch a campaign
              </Button>
            </Link>
          }
          className="py-20"
        />
      ) : (
        <>
          {/* Hero strip of headline findings */}
          {hero.length > 0 && (
            <div>
              <SectionTitle>Headline findings</SectionTitle>
              <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-4">
                {hero.map((ins) => (
                  <HeroCard key={ins.kind} insight={ins} />
                ))}
                {/* pad the strip if we have fewer than 4 headline findings */}
                {hero.length < 4 &&
                  Array.from({ length: 4 - hero.length }).map((_, i) => (
                    <Card
                      key={`pad-${i}`}
                      className="flex items-center justify-center border-dashed py-6 text-center"
                    >
                      <div className="px-4 text-xs text-muted-foreground">
                        More headline findings appear as volume grows.
                      </div>
                    </Card>
                  ))}
              </div>
            </div>
          )}

          {/* Full ranked list of insights */}
          <div>
            <SectionTitle
              action={
                <span className="flex items-center gap-1.5 text-xs text-muted-foreground">
                  <Sparkles className="size-3.5" /> Sorted by confidence
                </span>
              }
            >
              All insights
            </SectionTitle>
            <div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">
              {sorted.map((ins) => (
                <InsightCard key={`${ins.kind}-${ins.title}`} insight={ins} />
              ))}
            </div>
          </div>

          {/* Method footnote */}
          <Card>
            <CardContent className="flex flex-wrap items-center gap-x-6 gap-y-2 p-4 text-xs text-muted-foreground">
              <span className="flex items-center gap-1.5 font-medium text-foreground">
                <BookOpen className="size-3.5" /> How to read this
              </span>
              <span>
                <span className="font-medium text-foreground">n</span> = sends backing the finding.
              </span>
              <span>
                <span className="text-success">High</span> ≥ 100 sends ·{" "}
                <span className="text-warning">Medium</span> ≥ 30 ·{" "}
                <span className="text-muted-foreground">Low</span> &lt; 30.
              </span>
              <span>
                Across all findings:{" "}
                <span className="tabular font-medium text-foreground">
                  {counts.totalSample.toLocaleString()}
                </span>{" "}
                sends analyzed.
              </span>
            </CardContent>
          </Card>
        </>
      )}
    </div>
  );
}

/* --------------------------------- Hero card ------------------------------ */
function HeroCard({ insight }: { insight: Insight }) {
  const meta = KIND_META[insight.kind];
  const Icon = meta.icon;
  const conf = CONFIDENCE_META[insight.confidence];
  return (
    <Card className="relative overflow-hidden p-4">
      <div
        className="absolute inset-x-0 top-0 h-0.5"
        style={{ background: meta.color }}
        aria-hidden
      />
      <div className="flex items-center justify-between">
        <span
          className="flex size-8 items-center justify-center rounded-lg"
          style={{
            backgroundColor: `color-mix(in oklch, ${meta.color} 14%, transparent)`,
            color: meta.color,
          }}
        >
          <Icon className="size-4" />
        </span>
        <Badge variant={conf.variant}>{insight.confidence}</Badge>
      </div>
      <div className="mt-3 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
        {meta.label}
      </div>
      <div className="mt-0.5 text-2xl font-semibold tabular" style={{ color: meta.color }}>
        {insight.metric}
      </div>
      <p className="mt-1 line-clamp-2 text-sm font-medium leading-snug">{insight.title}</p>
    </Card>
  );
}

/* -------------------------------- Insight card ---------------------------- */
function InsightCard({ insight }: { insight: Insight }) {
  const meta = KIND_META[insight.kind];
  const Icon = meta.icon;
  const conf = CONFIDENCE_META[insight.confidence];
  return (
    <Card className="flex h-full flex-col p-5 transition-shadow hover:shadow-md">
      <div className="flex items-start justify-between gap-3">
        <div className="flex min-w-0 items-start gap-3">
          <span
            className="flex size-9 shrink-0 items-center justify-center rounded-lg"
            style={{
              backgroundColor: `color-mix(in oklch, ${meta.color} 14%, transparent)`,
              color: meta.color,
            }}
          >
            <Icon className="size-4.5" />
          </span>
          <div className="min-w-0">
            <div className="text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
              {meta.label}
            </div>
            <h3 className="mt-0.5 text-sm font-semibold leading-snug">{insight.title}</h3>
          </div>
        </div>
        <div className="text-2xl font-semibold tabular leading-none" style={{ color: meta.color }}>
          {insight.metric}
        </div>
      </div>

      <p className="mt-3 flex-1 text-sm leading-relaxed text-muted-foreground">{insight.detail}</p>

      <div className="mt-4 flex items-center justify-between border-t border-border pt-3">
        <Badge variant={conf.variant} dot={confDot(insight.confidence)}>
          {conf.label}
        </Badge>
        <span
          className={cn(
            "flex items-center gap-1 text-xs font-medium tabular text-muted-foreground",
          )}
          title={`${insight.sampleSize} sends support this finding`}
        >
          <Sigma className="size-3" />n = {insight.sampleSize.toLocaleString()}
        </span>
      </div>
    </Card>
  );
}

function confDot(c: Insight["confidence"]): string {
  return c === "high"
    ? "var(--success)"
    : c === "medium"
      ? "var(--warning)"
      : "var(--muted-foreground)";
}
